plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - unlockthecity/technicaldebt.md
  - unlockthecity/factoryreset.md
  - unlockthecity/protectthesupply.md
